### ISSUE TITLE
s3 complete_multipart_upload errors out

### ISSUE THREAD

**Issue by itajaja** [spulec/moto#4100]
works on 2.1.0, fails on 2.2.0. installed using poetry, but I don't think makes any difference. I will try to make a minimum reproducible example

here is the full stack trace from pytest

```
self.s3_client.complete_multipart_upload(
.venv/lib/python3.9/site-packages/botocore/client.py:386: in _api_call
    return self._make_api_call(operation_name, kwargs)
.venv/lib/python3.9/site-packages/botocore/client.py:691: in _make_api_call
    http, parsed_response = self._make_request(
.venv/lib/python3.9/site-packages/botocore/client.py:711: in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
.venv/lib/python3.9/site-packages/botocore/endpoint.py:102: in make_request
    return self._send_request(request_dict, operation_model)
.venv/lib/python3.9/site-packages/botocore/endpoint.py:136: in _send_request
    while self._needs_retry(attempts, operation_model, request_dict,
.venv/lib/python3.9/site-packages/botocore/endpoint.py:253: in _needs_retry
    responses = self._event_emitter.emit(
.venv/lib/python3.9/site-packages/botocore/hooks.py:356: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
.venv/lib/python3.9/site-packages/botocore/hooks.py:228: in emit
    return self._emit(event_name, kwargs)
.venv/lib/python3.9/site-packages/botocore/hooks.py:211: in _emit
    response = handler(**kwargs)
.venv/lib/python3.9/site-packages/botocore/retryhandler.py:183: in __call__
    if self._checker(attempts, response, caught_exception):
.venv/lib/python3.9/site-packages/botocore/retryhandler.py:250: in __call__
    should_retry = self._should_retry(attempt_number, response,
.venv/lib/python3.9/site-packages/botocore/retryhandler.py:269: in _should_retry
    return self._checker(attempt_number, response, caught_exception)
.venv/lib/python3.9/site-packages/botocore/retryhandler.py:316: in __call__
    checker_response = checker(attempt_number, response,
.venv/lib/python3.9/site-packages/botocore/retryhandler.py:222: in __call__
    return self._check_caught_exception(
.venv/lib/python3.9/site-packages/botocore/retryhandler.py:359: in _check_caught_exception
    raise caught_exception
.venv/lib/python3.9/site-packages/botocore/endpoint.py:197: in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
.venv/lib/python3.9/site-packages/botocore/hooks.py:356: in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
.venv/lib/python3.9/site-packages/botocore/hooks.py:228: in emit
    return self._emit(event_name, kwargs)
.venv/lib/python3.9/site-packages/botocore/hooks.py:211: in _emit
    response = handler(**kwargs)
.venv/lib/python3.9/site-packages/moto/core/models.py:368: in __call__
    status, headers, body = response_callback(
.venv/lib/python3.9/site-packages/moto/s3/responses.py:254: in ambiguous_response
    return self.key_or_control_response(request, full_url, headers)
.venv/lib/python3.9/site-packages/moto/s3/responses.py:1005: in key_or_control_response
    response = self._key_response(request, full_url, headers)
.venv/lib/python3.9/site-packages/moto/s3/responses.py:1176: in _key_response
    return self._key_response_post(request, body, bucket_name, query, key_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <moto.s3.responses.ResponseObject object at 0x11ad81250>
request = <AWSPreparedRequest stream_output=False, method=POST, url=https://bucket-test.s3.amazonaws.com/f1?uploadId=id1, header...4ab9a3ac8d3a2cfa031fb0b90828191992ab18c00842afabcd0', 'Content-Length': '183', 'host': 'bucket-test.s3.amazonaws.com'}>
body = <generator object ResponseObject._complete_multipart_body at 0x11c1b97b0>, bucket_name = 'bucket-test'
query = {'uploadId': ['id1']}, key_name = 'f1'

    def _key_response_post(self, request, body, bucket_name, query, key_name):
        self._set_action("KEY", "POST", query)
        self._authenticate_and_authorize_s3_action()

        if body == b"" and "uploads" in query:
            metadata = metadata_from_headers(request.headers)
            multipart = FakeMultipart(key_name, metadata)
            multipart.storage = request.headers.get("x-amz-storage-class", "STANDARD")

            bucket = self.backend.get_bucket(bucket_name)
            bucket.multiparts[multipart.id] = multipart

            template = self.response_template(S3_MULTIPART_INITIATE_RESPONSE)
            response = template.render(
                bucket_name=bucket_name, key_name=key_name, upload_id=multipart.id
            )
            return 200, {}, response

        if query.get("uploadId"):
            body = self._complete_multipart_body(body)
            multipart_id = query["uploadId"][0]

            bucket = self.backend.get_bucket(bucket_name)
            multipart = bucket.multiparts[multipart_id]
            value, etag = multipart.complete(body)
            if value is None:
                return 400, {}, ""

            del bucket.multiparts[multipart_id]

            key = self.backend.set_object(
                bucket_name,
                multipart.key_name,
                value,
>               storage=multipart.storage,
                etag=etag,
                multipart=multipart,
            )
E           AttributeError: 'FakeMultipart' object has no attribute 'storage'

.venv/lib/python3.9/site-packages/moto/s3/responses.py:1802: AttributeError
```

**Comment by itajaja** [comment]
looks like the offending change was in this rather big PR: https://github.com/spulec/moto/pull/4082/files#diff-a14f7ca014b23638947c5f417dacb9a4d59eef3aee9a8041e2c855e8587643cdR1802

**Comment by bblommers** [comment]
Hi @itajaja, thanks for raising this! A minimum reproducible example would be very helpful, as none of our tests/use cases picked this bug up.

**Comment by itajaja** [comment]
closing this. I was not using moto properly, and was circumventing some logic ✌️

**Comment by bblommers** [comment]
Happy to hear that it waai our fault. 🙂 
Are you able to share some details on how this error occurred? Even if the logic was wrong, Moto still shouldn't throw any AttributeError

**Comment by itajaja** [comment]
sure. Instead of simulating uploading parts by calling `upload_part`, I was explicitly creating a `FakeMultipart` upload manually and adding it to the moto backends. the problem is that with the new version, I would need to add an additional `storage` property to that object. I changed testing approach so that I actually call `upload_part` in my tests

**Comment by bblommers** [comment]
Ah, gotcha - that makes sense. Thanks for the explanation!
