### ISSUE TITLE
'NetworkInterface' object has no attribute 'private_dns_name'

### ISSUE THREAD

**Issue by gnarledglobe** [spulec/moto#9089]
Hello,

After updating from Moto 5.1.6 to 5.1.8, I get the following:

```
...
/var/lang/lib/python3.12/site-packages/botocore/hooks.py:239: in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
/var/lang/lib/python3.12/site-packages/moto/core/botocore_stubber.py:38: in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/var/lang/lib/python3.12/site-packages/moto/core/botocore_stubber.py:88: in process_request
    status, headers, body = method_to_execute(
/var/lang/lib/python3.12/site-packages/moto/core/responses.py:355: in dispatch
    return cls()._dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
/var/lang/lib/python3.12/site-packages/moto/core/responses.py:567: in _dispatch
    return self.call_action()
           ^^^^^^^^^^^^^^^^^^
/var/lang/lib/python3.12/site-packages/moto/core/responses.py:666: in call_action
    response = method()
               ^^^^^^^^
/var/lang/lib/python3.12/site-packages/moto/ecs/responses.py:186: in run_task
    tasks = self.ecs_backend.run_task(
/var/lang/lib/python3.12/site-packages/moto/ecs/models.py:1403: in run_task
    task = Task(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <moto.ecs.models.Task object at 0x7ad667a82360>, cluster = <moto.ecs.models.Cluster object at 0x7ad66cc16780>, task_definition = <moto.ecs.models.TaskDefinition object at 0x7ad66592d220>, container_instance_arn = None, resource_requirements = {'CPU': 256, 'MEMORY': 512, 'PORTS': [], 'PORTS_UDP': []}
backend = <moto.ecs.models.EC2ContainerServiceBackend object at 0x7ad66f06bb00>, launch_type = 'FARGATE', overrides = {'containerOverrides': [{'command': ['poetry', 'run', 'camena', 'cimban', 'make-design', '--input-file-path', ...], 'name': 'cimban'}]}, started_by = '', tags = []
networking_configuration = {'awsvpcConfiguration': {'assignPublicIp': 'ENABLED', 'securityGroups': ['sg_23742832'], 'subnets': ['subnet-e1b2c5c03db4d8f0e']}}

    def __init__(
        self,
        cluster: Cluster,
        task_definition: TaskDefinition,
        container_instance_arn: Optional[str],
        resource_requirements: Optional[Dict[str, str]],
        backend: "EC2ContainerServiceBackend",
        launch_type: str = "",
        overrides: Optional[Dict[str, Any]] = None,
        started_by: str = "",
        tags: Optional[List[Dict[str, str]]] = None,
        networking_configuration: Optional[Dict[str, Any]] = None,
    ):
        # Configure ManagedState
        # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-lifecycle.html
        super().__init__(
            model_name="ecs::task",
            transitions=[
                # We start in RUNNING state in order not to break existing tests.
                # ("PROVISIONING", "PENDING"),
                # ("PENDING", "ACTIVATING"),
                # ("ACTIVATING", "RUNNING"),
                ("RUNNING", "DEACTIVATING"),
                ("DEACTIVATING", "STOPPING"),
                ("STOPPING", "DEPROVISIONING"),
                ("DEPROVISIONING", "STOPPED"),
                # There seems to be race condition, where the waiter expects the task to be in
                # STOPPED state, but it is already in DELETED state.
                # ("STOPPED", "DELETED"),
            ],
        )
        self.id = str(mock_random.uuid4())
        self.cluster_name = cluster.name
        self.cluster_arn = cluster.arn
        self.container_instance_arn = container_instance_arn
        self.desired_status = "RUNNING"
        self.task_definition_arn = task_definition.arn
        self.overrides = overrides or {}
        self.containers = [Container(task_definition)]
        self.started_by = started_by
        self.tags = tags or []
        self.launch_type = launch_type
        self.stopped_reason = ""
        self.resource_requirements = resource_requirements
        self.region_name = cluster.region_name
        self._account_id = backend.account_id
        self._backend = backend
        self.attachments = []
    
        if task_definition.network_mode == "awsvpc":
            if not networking_configuration:
                raise InvalidParameterException(
                    "Network Configuration must be provided when networkMode 'awsvpc' is specified."
                )
    
            self.network_configuration = networking_configuration
            net_conf = networking_configuration["awsvpcConfiguration"]
            ec2_backend = ec2_backends[self._account_id][self.region_name]
    
            eni = ec2_backend.create_network_interface(
                subnet=net_conf["subnets"][0],
                private_ip_address=random_private_ip(),
                group_ids=net_conf["securityGroups"],
                description="moto ECS",
            )
            eni.status = "in-use"
            eni.device_index = 0
    
            self.attachments.append(
                {
                    "id": str(mock_random.uuid4()),
                    "type": "ElasticNetworkInterface",
                    "status": "ATTACHED",
                    "details": [
                        {"name": "subnetId", "value": net_conf["subnets"][0]},
                        {"name": "networkInterfaceId", "value": eni.id},
                        {"name": "macAddress", "value": eni.mac_address},
>                       {"name": "privateDnsName", "value": eni.private_dns_name},
                                                            ^^^^^^^^^^^^^^^^^^^^
                        {"name": "privateIPv4Address", "value": eni.private_ip_address},
                    ],
                }
            )
E           AttributeError: 'NetworkInterface' object has no attribute 'private_dns_name'
```

My test fixtures are:
```
@pytest.fixture
def mock_ecs_cluster_arn(
    mock_aws_: None,  # noqa: ARG001 Unused function argument: `mock_aws_`
    monkeypatch: pytest.MonkeyPatch,
) -> str:
    aws_client = boto3.client("ecs")
    ecs_cluster = aws_client.create_cluster(clusterName="test-cluster-name")
    monkeypatch.setenv("FARGATE_CIMBAN_ECS_CLUSTER_ARN", ecs_cluster["cluster"]["clusterArn"])
    return ecs_cluster["cluster"]["clusterArn"]


@pytest.fixture
def mock_vpc_id(mock_aws_: None) -> str:  # noqa: ARG001 Unused function argument: `mock_aws_`
    aws_client = boto3.client("ec2")
    vpc = aws_client.create_vpc(CidrBlock="10.0.0.0/16")
    return vpc["Vpc"]["VpcId"]  # type: ignore[no-any-return]


@pytest.fixture
def mock_subnet_id(
    mock_aws_: None,  # noqa: ARG001 Unused function argument: `mock_aws_`
    mock_vpc_id: str,
    monkeypatch: pytest.MonkeyPatch,
) -> str:
    aws_client = boto3.client("ec2")
    subnet = aws_client.create_subnet(VpcId=mock_vpc_id, CidrBlock="10.0.0.0/16")
    monkeypatch.setenv("FARGATE_CIMBAN_TASK_SUBNET_ID", subnet["Subnet"]["SubnetId"])
    return subnet["Subnet"]["SubnetId"]  # type: ignore[no-any-return]


@pytest.fixture
def mock_ecs_task_arn(
    mock_aws_: None,  # noqa: ARG001 Unused function argument: `mock_aws_`
    mock_subnet_id: str,  # noqa: ARG001 Unused function argument: `mock_subnet_id`
    mock_ecs_cluster_arn: str,  # noqa: ARG001 Unused function argument: `mock_ecs_cluster_arn`
    monkeypatch: pytest.MonkeyPatch,
) -> str:
    aws_client = boto3.client("ecs")
    task_definition = aws_client.register_task_definition(
        family="test-task-family",
        networkMode="awsvpc",
        requiresCompatibilities=["FARGATE"],
        containerDefinitions=[
            {"name": "test-switch-off", "image": "hello-world:latest", "cpu": 256, "memory": 512, "essential": True}
        ],
    )
    monkeypatch.setenv("FARGATE_CIMBAN_ECS_TASK_DEFINITION_ARN", task_definition["taskDefinition"]["taskDefinitionArn"])
    return task_definition["taskDefinition"]["taskDefinitionArn"]
```

Any help would be greatly appreciated!

**Comment by bpandola** [comment]
Can you try enabling DNS hostnames for your VPC?

```python
ec2_client.modify_vpc_attribute(VpcId=[your vpc id], EnableDnsHostnames={"Value": True})
```

I think you might've been relying on previously incorrect Moto behavior (fixed in #9027) where this was turned on by default.

**Comment by gnarledglobe** [comment]
Yes that works! Thanks very much for the quick reply and help, sorry I missed the PR!
