### ISSUE TITLE
unittest.TestCase class decorators broken in moto 1.3.16 (worked in 1.3.14)

### ISSUE THREAD

**Issue by xinxinw1** [spulec/moto#3594]
Using a class decorator seems to be trying to stop an internal `mock.patch` twice, causing errors like `AttributeError: '_patch' object has no attribute 'is_local'` with mock==4.0.3 and the more clearer `RuntimeError: stop called on unstarted patcher` with mock==2.0.0.

I believe the cause is https://github.com/spulec/moto/pull/2578 which adds a `mock.patch("boto3.DEFAULT_SESSION", None)` which gets started twice and stopped twice when running tests with a class mock on a unittest.TestCase

## Steps to reproduce

Run `pip install boto moto pytest sure` in a clean python3 virtualenv, and run pytest with the following test file:

(This is actually the same code that's in moto's own decorator tests so I'm surprised this passes there but fails in an outside environment: https://github.com/spulec/moto/blob/master/tests/test_core/test_decorator_calls.py#L79)

```python
import unittest
import pytest
from moto import mock_s3_deprecated
import boto
import sure

@mock_s3_deprecated
class TesterWithSetup(unittest.TestCase):
    def setUp(self):
        self.conn = boto.connect_s3()
        self.conn.create_bucket("mybucket")

    def test_still_the_same(self):
        bucket = self.conn.get_bucket("mybucket")
        bucket.name.should.equal("mybucket")
```

Here are the relevant package versions as of the creation time of this issue:

```
boto==2.49.0
boto3==1.16.56
botocore==1.19.56
mock==4.0.3
moto==1.3.16
pytest==6.2.1
sure==1.4.11
```

## Traceback

```
(vendor3) st-xinxin1:test-virtualenv xinxin$ pytest test_moto.py
==================================================================================================================== test session starts =====================================================================================================================
platform darwin -- Python 3.7.3, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/xinxin/stripe/test-virtualenv
collected 1 item

test_moto.py F                                                                                                                                                                                                                                         [100%]

========================================================================================================================== FAILURES ==========================================================================================================================
____________________________________________________________________________________________________________ TesterWithSetup.test_still_the_same _____________________________________________________________________________________________________________
vendor3/lib/python3.7/site-packages/moto/core/models.py:102: in wrapper
    self.stop()
vendor3/lib/python3.7/site-packages/moto/core/models.py:86: in stop
    self.default_session_mock.stop()
vendor3/lib/python3.7/site-packages/mock/mock.py:1563: in stop
    return self.__exit__(None, None, None)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <mock.mock._patch object at 0x1055191d0>, exc_info = (None, None, None)

    def __exit__(self, *exc_info):
        """Undo the patch."""
>       if self.is_local and self.temp_original is not DEFAULT:
E       AttributeError: '_patch' object has no attribute 'is_local'

vendor3/lib/python3.7/site-packages/mock/mock.py:1529: AttributeError
====================================================================================================================== warnings summary ======================================================================================================================
vendor3/lib/python3.7/site-packages/boto/plugin.py:40
  /Users/xinxin/stripe/test-virtualenv/vendor3/lib/python3.7/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

vendor3/lib/python3.7/site-packages/sure/old.py:26
  /Users/xinxin/stripe/test-virtualenv/vendor3/lib/python3.7/site-packages/sure/old.py:26: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================================================================== short test summary info ===================================================================================================================
FAILED test_moto.py::TesterWithSetup::test_still_the_same - AttributeError: '_patch' object has no attribute 'is_local'
=============================================================================================================== 1 failed, 2 warnings in 0.66s ================================================================================================================
```

A project I'm seeing this in uses mock==2.0.0 which gives this error instead:

```
(vendor3) st-xinxin1:test-virtualenv xinxin$ pip install mock==2.0.0
[...]
Successfully installed mock-2.0.0 pbr-5.5.1
(vendor3) st-xinxin1:test-virtualenv xinxin$ pytest test_moto.py
==================================================================================================================== test session starts =====================================================================================================================
platform darwin -- Python 3.7.3, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/xinxin/stripe/test-virtualenv
collected 1 item

test_moto.py F                                                                                                                                                                                                                                         [100%]

========================================================================================================================== FAILURES ==========================================================================================================================
____________________________________________________________________________________________________________ TesterWithSetup.test_still_the_same _____________________________________________________________________________________________________________
vendor3/lib/python3.7/site-packages/moto/core/models.py:102: in wrapper
    self.stop()
vendor3/lib/python3.7/site-packages/moto/core/models.py:86: in stop
    self.default_session_mock.stop()
vendor3/lib/python3.7/site-packages/mock/mock.py:1513: in stop
    return self.__exit__()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <mock.mock._patch object at 0x1031a6828>, exc_info = ()

    def __exit__(self, *exc_info):
        """Undo the patch."""
        if not _is_started(self):
>           raise RuntimeError('stop called on unstarted patcher')
E           RuntimeError: stop called on unstarted patcher

vendor3/lib/python3.7/site-packages/mock/mock.py:1477: RuntimeError
====================================================================================================================== warnings summary ======================================================================================================================vendor3/lib/python3.7/site-packages/boto/plugin.py:40
  /Users/xinxin/stripe/test-virtualenv/vendor3/lib/python3.7/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

vendor3/lib/python3.7/site-packages/sure/old.py:26
  /Users/xinxin/stripe/test-virtualenv/vendor3/lib/python3.7/site-packages/sure/old.py:26: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable

-- Docs: https://docs.pytest.org/en/stable/warnings.html
================================================================================================================== short test summary info ===================================================================================================================
FAILED test_moto.py::TesterWithSetup::test_still_the_same - RuntimeError: stop called on unstarted patcher
=============================================================================================================== 1 failed, 2 warnings in 0.77s ================================================================================================================
```

Using moto 1.3.14 works:

```
(vendor3) st-xinxin1:test-virtualenv xinxin$ pip install moto==1.3.14
[...]
Successfully installed idna-2.8 jsondiff-1.1.2 moto-1.3.14
(vendor3) st-xinxin1:test-virtualenv xinxin$ pytest test_moto.py
==================================================================================================================== test session starts =====================================================================================================================
platform darwin -- Python 3.7.3, pytest-6.2.1, py-1.10.0, pluggy-0.13.1
rootdir: /Users/xinxin/stripe/test-virtualenv
collected 1 item

test_moto.py .                                                                                                                                                                                                                                         [100%]

====================================================================================================================== warnings summary ======================================================================================================================
vendor3/lib/python3.7/site-packages/boto/plugin.py:40
  /Users/xinxin/stripe/test-virtualenv/vendor3/lib/python3.7/site-packages/boto/plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

vendor3/lib/python3.7/site-packages/moto/cloudformation/parsing.py:407
  /Users/xinxin/stripe/test-virtualenv/vendor3/lib/python3.7/site-packages/moto/cloudformation/parsing.py:407: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    class ResourceMap(collections.Mapping):

vendor3/lib/python3.7/site-packages/sure/old.py:26
  /Users/xinxin/stripe/test-virtualenv/vendor3/lib/python3.7/site-packages/sure/old.py:26: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
    from collections import Iterable

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=============================================================================================================== 1 passed, 3 warnings in 2.52s ================================================================================================================
```

**Comment by bblommers** [comment]
Hi @xinxinw1, thanks for raising this, and providing the detailed stack traces. I believe this is a duplicate of #3535, so I'll close this one.

FYI: This bug only popped up after mock 4.0.3 was released, so it should work as long as you pin the version to 4.0.2.
