### ISSUE TITLE
mocking of test assume role and Account Id not working

### ISSUE THREAD

**Issue by manas86** [spulec/moto#3001]
1.  Account ID not working

when using `from moto.core import ACCOUNT_ID`  python complaining 
ImportError: cannot import name 'ACCOUNT_ID' from 'moto.core' 
also tried to use environment variable MOTO_ACCOUNT_ID still not working? 

2.  Test Assume Role complaining 
```
 assume_role_response = sts_resource.assume_role(
AttributeError: 'function' object has no attribute 'assume_role'
```
I have taken the code snippet for testing assume role from [https://github.com/spulec/moto/blob/master/tests/test_sts/test_sts.py]@test_assume_role since account id is not working I replaced with 123456789012

```
@pytest.fixture
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ['AWS_ACCESS_KEY_ID'] = 'testing'
    os.environ['AWS_SECRET_ACCESS_KEY'] = 'testing'
    os.environ['AWS_SECURITY_TOKEN'] = 'testing'
    os.environ['AWS_SESSION_TOKEN'] = 'testing'
    os.environ['RELEASE_ENVIRONMENTNAME'] = 'local'

@pytest.fixture()
def sts_resource(aws_credentials):
    mock = mock_sts()
    mock.start()
    yield boto3.resource('sts', region_name='eu-west-1')
    mock.stop()

def test_assume_role(sts_resource):
    # client = boto3.client("sts", region_name="us-east-1")

    session_name = "session-name"
    policy = json.dumps(
        {
            "Statement": [
                {
                    "Sid": "Stmt13690092345534",
                    "Action": ["S3:ListBucket"],
                    "Effect": "Allow",
                    "Resource": ["arn:aws:s3:::foobar-tester"],
                }
            ]
        }
    )
    role_name = "test-role"
    s3_role = "arn:aws:iam::{account_id}:role/{role_name}".format(
        account_id=123456789012, role_name=role_name
    )
    assume_role_response = sts_resource.assume_role(
        RoleArn=s3_role,
        RoleSessionName=session_name,
        Policy=policy,
        DurationSeconds=900,
    )

    credentials = assume_role_response["Credentials"]
    print(credentials)

if __name__ == '__main__':
   test_assume_role(sts_resource)
```

**Comment by bblommers** [comment]
Hi @manas86. Regarding 2), only the STS client supports the assume_role method - not the resource.
Should work just fine with `yield boto3.client('sts', region_name='eu-west-1')`

Regarding 1), I'd have to do some digging why that doesn't work. I'll get back to you on that.

**Comment by manas86** [comment]
@bblommers thanks for the query no1. However query number 2 is still showing the same behavior even after changing it to `client `instead of `resource`.  similar issue is with `iam ` as well. unless im doing something stupid. 

```
  assume_role_response = sts.assume_role(
AttributeError: 'function' object has no attribute 'assume_role' 
```
now test.py looks like below, 
```
@pytest.fixture
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ['AWS_ACCESS_KEY_ID'] = 'testing'
    os.environ['AWS_SECRET_ACCESS_KEY'] = 'testing'
    os.environ['AWS_SECURITY_TOKEN'] = 'testing'
    os.environ['AWS_SESSION_TOKEN'] = 'testing'
    os.environ['RELEASE_ENVIRONMENTNAME'] = 'local'

@pytest.fixture(scope='function')
def sts(aws_credentials):
    with mock_sts():
        yield boto3.client('sts', region_name='eu-west-1')

def test_assume_role(sts):
    session_name = "session-name"
    policy = json.dumps(
        {
            "Statement": [
                {
                    "Sid": "Stmt13690092345534",
                    "Action": ["S3:ListBucket"],
                    "Effect": "Allow",
                    "Resource": ["arn:aws:s3:::foobar-tester"],
                }
            ]
        }
    )
    role_name = "test-role"
    s3_role = "arn:aws:iam::{account_id}:role/{role_name}".format(
        account_id=123456789012, role_name=role_name
    )
    assume_role_response = sts.assume_role(
        RoleArn=s3_role,
        RoleSessionName=session_name,
        Policy=policy,
        DurationSeconds=900,
    )

    credentials = assume_role_response["Credentials"]
    print(credentials["SessionToken"])
    print(assume_role_response["AssumedRoleUser"]["Arn"])


if __name__ == '__main__':
    test_assume_role(sts)
```
any help will be appreciated.

**Comment by bblommers** [comment]
Interestingly, as above works fine for me.

You're passing in the sts-function in `main` though, which might confuse Pytest to think it doesn't need to use the fixture. That would explain the error message - it tries to execute `assume_role` on the sts-function itself.

Does this work better?
```
if __name__ == '__main__':
    test_assume_role()
```

**Comment by manas86** [comment]
@bblommers sorry I should have mentioned that earlier , I tried earlier without the argument, and for me , it says 
`TypeError: test_assume_role() missing 1 required positional argument: 'sts'` . I'm surprised that it works for you. 
so, that's why it's strange. I'm working with Intellij IDE with python 3.8

**Comment by bblommers** [comment]
OK, I now got the same error. Not sure how why it worked earlier.

The problem for me is that Pytest isn't initializing properly when the script is executed as a 'pure' Python script. When removing the main-statement and running it as a test (either in PyCharm or on the command line, `pytest test.py`), this works:
```
import boto3
import json
import pytest
import os

from moto import mock_sts


@pytest.fixture
def aws_credentials():
    """Mocked AWS Credentials for moto."""
    os.environ['AWS_ACCESS_KEY_ID'] = 'testing'
    os.environ['AWS_SECRET_ACCESS_KEY'] = 'testing'
    os.environ['AWS_SECURITY_TOKEN'] = 'testing'
    os.environ['AWS_SESSION_TOKEN'] = 'testing'
    os.environ['RELEASE_ENVIRONMENTNAME'] = 'local'


@pytest.fixture(scope='function')
def sts(aws_credentials):
    with mock_sts():
        yield boto3.client('sts', region_name='eu-west-1')


def test_assume_role(sts):
    session_name = "session-name"
    policy = json.dumps(
        {
            "Statement": [
                {
                    "Sid": "Stmt13690092345534",
                    "Action": ["S3:ListBucket"],
                    "Effect": "Allow",
                    "Resource": ["arn:aws:s3:::foobar-tester"],
                }
            ]
        }
    )
    role_name = "test-role"
    s3_role = "arn:aws:iam::{account_id}:role/{role_name}".format(
        account_id=123456789012, role_name=role_name
    )
    assume_role_response = sts.assume_role(
        RoleArn=s3_role,
        RoleSessionName=session_name,
        Policy=policy,
        DurationSeconds=900,
    )
    print(assume_role_response["AssumedRoleUser"]["Arn"])
```

**Comment by hkhrais** [comment]
I also have problem with using `MOTO_ACCOUNT_ID` as os environ. No matter what value i set there, it always get the default "123456789012" . Iam using Pycharm and here is a snippet of how i do it 

```
import os
os.environ['MOTO_ACCOUNT_ID'] = "444444444"
from moto import mock_dynamodb2, mock_sqs

```
then i create sqs and when i mock my actual code which looks for sqs url in account 444444444, it says it doesn't exist as created in "123456789012".
Any idea?

**Comment by hkhrais** [comment]
NVM, i cloned the repo and placed it in site-packages and worked fine.
