### PR TITLE
SNS: Fix incomplete conversions of boolean values

### PR DESCRIPTION
**Pull request by viren-nadkarni**
This PR fixes some regressions that appeared after https://github.com/getmoto/moto/pull/9642.

Specifically:
- Occurence of `AttributeError: 'bool' object has no attribute 'lower'` when invoking `SetEndpointAttributes`
- Boolean values incorrectly returned as `True` or `False` (expected `true` and `false`) when invoking `ListEndpointsByPlatformApplication` and `ListPlatformApplications`

### CODE REVIEW

File: moto/sns/models.py [hunk 1]
```diff
@@ -869,7 +870,7 @@ def set_endpoint_attributes(
     ) -> PlatformEndpoint:
         endpoint = self.get_endpoint(arn)
         if "Enabled" in attributes:
-            attributes["Enabled"] = attributes["Enabled"].lower()
+            attributes["Enabled"] = ensure_boolean(attributes["Enabled"])
```
Comment (bpandola) [inline moto/sns/models.py]: We should be able to delete this conditional entirely, no?  This attribute should already have been coerced to `bool` in `responses.py`.

**Review by bpandola — CHANGES_REQUESTED** [review]
@viren-nadkarni Thank you for closing the loop on this.  I have one minor request and then happy to merge.

P.S. I'd love to be able to run Localstack's test suite against Moto changes to catch regressions like this, but I'm guessing the bulk of your tests are not open source, right?

**Comment by bblommers** [comment]
> P.S. I'd love to be able to run Localstack's test suite against Moto changes to catch regressions like this, but I'm guessing the bulk of your tests are not open source, right?

@bpandola The vast majority of SNS tests is actually open source*: https://github.com/localstack/localstack/tree/main/tests/aws/services/sns 

Don't know how easy it is to run this against Moto though :eyes: 

*For now at least - [this will change in March 2026](https://blog.localstack.cloud/the-road-ahead-for-localstack/#what-is-changing)

**Comment by viren-nadkarni** [comment]
@bpandola Thanks for pushing this through :raised_hands:

**Comment by bpandola** [comment]
> @bpandola The vast majority of SNS tests is actually open source*: https://github.com/localstack/localstack/tree/main/tests/aws/services/sns
> 
> Don't know how easy it is to run this against Moto though 👀
> 
> *For now at least - [this will change in March 2026](https://blog.localstack.cloud/the-road-ahead-for-localstack/#what-is-changing)

@bblommers Yeah, probably just wishful thinking on my part...  It seemed unfortunate to me that they have all this extra test coverage that could (and did in this case) catch a Moto regression, but the feedback loop is manual (and of course leaves them at the mercy of whatever changes we make possibly breaking them).  I felt like there should be some way to automate that check for the benefit of both communities, but that appears to be moot given the link you mentioned and the note I recently saw that they decided to hard fork Moto.
