### ISSUE TITLE
Version 1.1.25 breakages

### ISSUE THREAD

**Issue by afgane** [spulec/moto#1357]
The 1.1.25 release seems to have introduced some undocumented changes that are breaking previously working builds. The same test harness run against real AWS infrastructure continues to function properly. I haven't dug into any of this but all the issues happen when upgrading from 1.1.24 to 1.1.25.

A link to Travis build is here with all the details: https://travis-ci.org/gvlproject/cloudbridge/jobs/305368221

Here are the highlights:

1. Image meta data object changed
```
Traceback (most recent call last):
  File "/Users/ea/projects/ppy/cb/cloudbridge/test/helpers/__init__.py", line 75, in wrapper
    func(self, *args, **kwargs)
  File "/Users/ea/projects/ppy/cb/cloudbridge/test/test_compute_service.py", line 264, in test_block_device_mapping_attachments
    size=img.min_disk if img and img.min_disk else 2,
  File "/Users/ea/projects/ppy/cb/cloudbridge/cloudbridge/cloud/providers/aws/resources.py", line 87, in min_disk
    self._ec2_image.block_device_mappings if
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/boto3/resources/factory.py", line 345, in property_loader
    return self.meta.data.get(name)
AttributeError: 'NoneType' object has no attribute 'get'
```

2. Image creation/list not returning values
```
Traceback (most recent call last):
  File "/Users/ea/projects/ppy/cb/cloudbridge/test/helpers/__init__.py", line 75, in wrapper
    func(self, *args, **kwargs)
  File "/Users/ea/projects/ppy/cb/cloudbridge/test/test_image_service.py", line 49, in test_create_and_list_image
    extra_test_func=extra_tests)
  File "/Users/ea/projects/ppy/cb/cloudbridge/test/helpers/standard_interface_tests.py", line 270, in check_crud
    check_standard_behaviour(test, service, obj)
  File "/Users/ea/projects/ppy/cb/cloudbridge/test/helpers/standard_interface_tests.py", line 157, in check_standard_behaviour
    objs_list = check_list(test, service, obj)
  File "/Users/ea/projects/ppy/cb/cloudbridge/test/helpers/standard_interface_tests.py", line 48, in check_list
    % (type(obj).__name__, obj.id, match_objs))
AssertionError: False is not true : List objects for AWSMachineImage does not return the expected object id ami-92b04e12. Got []
```

3. ipaddress cidr block representation
```
Traceback (most recent call last):
  File "/Users/ea/projects/ppy/cb/cloudbridge/test/helpers/__init__.py", line 42, in cleanup_action
    yield
  File "/Users/ea/projects/ppy/cb/cloudbridge/test/helpers/standard_interface_tests.py", line 267, in check_crud
    obj = create_func(name)
  File "/Users/ea/projects/ppy/cb/cloudbridge/test/test_network_service.py", line 79, in create_subnet
    network=net, cidr_block="10.0.0.1/24", name=name)
  File "/Users/ea/projects/ppy/cb/cloudbridge/cloudbridge/cloud/providers/aws/services.py", line 683, in create
    AvailabilityZone=zone)
  File "/Users/ea/projects/ppy/cb/cloudbridge/cloudbridge/cloud/providers/aws/helpers.py", line 266, in create
    result = getattr(self.boto_conn, boto_method)(**trimmed_args)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/client.py", line 599, in _make_api_call
    operation_model, request_dict)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/endpoint.py", line 143, in make_request
    return self._send_request(request_dict, operation_model)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/endpoint.py", line 172, in _send_request
    success_response, exception):
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/endpoint.py", line 265, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/retryhandler.py", line 251, in __call__
    caught_exception)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/retryhandler.py", line 269, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/retryhandler.py", line 317, in __call__
    caught_exception)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/endpoint.py", line 213, in _get_response
    proxies=self.proxies, timeout=self.timeout)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/botocore/vendored/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/moto/packages/responses/responses.py", line 308, in unbound_on_send
    return self._on_request(adapter, request, *a, **kwargs)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/moto/packages/responses/responses.py", line 261, in _on_request
    status, r_headers, body = match['callback'](request)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/moto/core/utils.py", line 170, in __call__
    result = self.callback(request, request.url, request.headers)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/moto/core/responses.py", line 114, in dispatch
    return cls()._dispatch(*args, **kwargs)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/moto/core/responses.py", line 182, in _dispatch
    return self.call_action()
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/moto/core/responses.py", line 256, in call_action
    response = method()
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/moto/ec2/responses/subnets.py", line 18, in create_subnet
    availability_zone,
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/moto/ec2/models.py", line 2318, in create_subnet
    default_for_az, map_public_ip_on_launch)
  File "/Users/ea/projects/ppy/cb/cloudbridge/.tox/py36-aws/lib/python3.6/site-packages/moto/ec2/models.py", line 2179, in __init__
    self.cidr = ipaddress.ip_network(six.text_type(self.cidr_block))
  File "/Users/ea/.pyenv/versions/3.6.2/lib/python3.6/ipaddress.py", line 74, in ip_network
    return IPv4Network(address, strict)
  File "/Users/ea/.pyenv/versions/3.6.2/lib/python3.6/ipaddress.py", line 1537, in __init__
    raise ValueError('%s has host bits set' % self)
ValueError: 10.0.0.1/24 has host bits set
```

**Comment by toshitanian** [comment]
Just took a look, #1331 has many changes related to AMI. We can check the changes in the PR.

**Comment by terrycain** [comment]
My bad. 

1 and 2, those traces are pretty much useless without examples, can you provide a test case for each.

As for .3 10.0.0.1/24 isnt a valid CIDR when creating a subnet. your after 10.0.0.0/24, though we probably want to add some error checking.

**Comment by afgane** [comment]
I'll try to find time to isolate the code that breaks the tests but at that point I might as well figure out how to update our test procedure to account for the changes since I'll have already spent the time. The core issue is that things were changed in the implementation but not documented as part of the release.

**Comment by william-richard** [comment]
https://github.com/spulec/moto/pull/1378 might be able to shed some light on examples 1 and 2 - the ami tests were not running as part of the regular test suite.  A few of the tests have been broken since release 1.0.0, but 1.1.25 did introduce new failures, especially around the ami filters.

**Comment by afgane** [comment]
Thanks for pointing this out. I did a bit more looking into this now and it does appear that earlier implementation was off on how AMI's were managed and now picking an ami from [amis.json](https://github.com/spulec/moto/blob/master/moto/ec2/resources/amis.json) fixes a couple of the tests.

**Comment by terrycain** [comment]
Ahh good spot, @william-richard I'll continue on your PR once you've finished what you can

**Comment by william-richard** [comment]
Thanks for the offer @terrycain - I think I managed to fix all of them.  As @afgane pointed out, a lot were just tweaking them to account for the pre-loaded amis from `amis.json`.  

I hope that I've also managed to fix some of the inconsistent changes introduced in 1.1.25 (at the very least, my personal uses of moto that were failing on 1.1.25 work with my branch), but I only focused on the paths and features that had test coverage, so there may be other cases that I didn't catch.
