### ISSUE TITLE
BUG: module 'moto.server' has no attribute 'backends' - moto 3.0.5 -> 3.0.7

### ISSUE THREAD

**Issue by dazza-codes** [spulec/moto#4937]
From moto 3.0.5 to 3.0.7, there seems to be breaking change introduced.

```
    def reset(self):
        # each service can have multiple regional backends
>       service_backends = moto.server.backends.get_backend(self._service_name)
E       AttributeError: module 'moto.server' has no attribute 'backends'
```

This was working fine with moto 3.0.5 but crashes with 3.0.7.  This is either a mistake, bug or a moto version that is breaking sem-ver expectations.

Can't find it anywhere:

```python
>>> import moto.server
>>> moto.server.backends
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'moto.server' has no attribute 'backends'

>>> import moto.moto_server
>>> import moto.moto_server.backends
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'moto.moto_server.backends'
>>> moto.moto_server.backends
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'moto.moto_server' has no attribute 'backends'
```

After dropping back to moto 3.0.5, it works:
```
$ poetry update moto  # pinned to 3.0.5 in pyproject.toml

  • Updating moto (3.0.7 -> 3.0.5)

$ python
Python 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import moto.server
>>> moto.server.backends
<module 'moto.backends' from '/opt/conda/envs/gis/lib/python3.7/site-packages/moto/backends.py'>
```

**Comment by bblommers** [comment]
Hi @dazza-codes, the `server.py` class imported the backends from `moto.backends`, so using that would be a more straightforward way to access these methods:

```
import moto.backends
moto.backends.get_backend("s3")
```

Does that solve your problem?

**Comment by bblommers** [comment]
> This is either a mistake, bug or a moto version that is breaking sem-ver expectations.
> 
I'm going to have to disagree there btw.. this is an internal import that we decided to move around. It is not part of the API, and it is not part of any documentation, so IMO there is no expectation that it will never change.

**Comment by dazza-codes** [comment]
Thanks, changing to `moto.backends` works out.

- `moto.server.backends` is not private
- `moto.server._backends` would have been private
