### ISSUE TITLE
Moto fails when event bridge client with list_rules invoked

### ISSUE THREAD

**Issue by dashsatish** [spulec/moto#3780]
## Reporting Bugs

Moto fails when event bridge client's `list_rules` invoked with `Limit` parameter

**Failure:**
```
self = <moto.events.models.EventsBackend object at 0x10cfd3df0>, index = 1

    def _gen_next_token(self, index):
>       token = os.urandom(128).encode("base64")
E       AttributeError: 'bytes' object has no attribute 'encode'
```

**How to reproduce:**
```
from moto import mock_events
import boto3
with mock_events():
    ev = boto3.client("events")
    ev.put_rule(Name="foo", ScheduleExpression="rate(1 day)")
    for i in range(5):
        ev.put_rule(Name=f"local-rule{i}", ScheduleExpression="rate(1 day)")
    res = ev.list_rules(NamePrefix="foo", Limit=2)
    print(res)


{"message": "Found credentials in environment variables.", "name": "botocore.credentials", "pathname": "***********/lib/python3.8/site-packages/botocore/credentials.py", "filename": "credentials.py", "module": "credentials", "exc_text": null, "stack_info": null, "created": 1616062235.3130748, "thread": 4477029824, "process": 57015, "timestamp": "2021-03-18T10:10:35.313075+00:00", "thread_name": "MainThread", "process_name": "MainProcess", "level_name": "INFO", "level_no": 20, "func_name": "load"}

{'RuleArn': 'arn:aws:events:us-east-1:111111111111:rule/foo', 'ResponseMetadata': {'HTTPStatusCode': 200, 'HTTPHeaders': {'server': 'amazon.com'}, 'RetryAttempts': 0}}

Traceback (most recent call last):
File "<stdin>", line 5, in <module>
File "***********/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "***********/lib/python3.8/site-packages/botocore/client.py", line 662, in _make_api_call
http, parsed_response = self._make_request(
    File "***********/lib/python3.8/site-packages/botocore/client.py", line 682, in _make_request
return self._endpoint.make_request(operation_model, request_dict)
File "***********/lib/python3.8/site-packages/botocore/endpoint.py", line 102, in make_request
return self._send_request(request_dict, operation_model)
File "***********/lib/python3.8/site-packages/botocore/endpoint.py", line 136, in _send_request
while self._needs_retry(attempts, operation_model, request_dict,
                        File "***********/lib/python3.8/site-packages/botocore/endpoint.py", line 253, in _needs_retry
responses = self._event_emitter.emit(
File "***********/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
return self._emitter.emit(aliased_event_name, **kwargs)
File "***********/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
return self._emit(event_name, kwargs)
File "***********/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
response = handler(**kwargs)
File "***********/lib/python3.8/site-packages/botocore/retryhandler.py", line 183, in __call__
if self._checker(attempts, response, caught_exception):
File "***********/lib/python3.8/site-packages/botocore/retryhandler.py", line 250, in __call__
should_retry = self._should_retry(attempt_number, response,
                                  File "***********/lib/python3.8/site-packages/botocore/retryhandler.py", line 269, in _should_retry
return self._checker(attempt_number, response, caught_exception)
File "***********/lib/python3.8/site-packages/botocore/retryhandler.py", line 316, in __call__
checker_response = checker(attempt_number, response,
                           File "***********/lib/python3.8/site-packages/botocore/retryhandler.py", line 222, in __call__
return self._check_caught_exception(
    File "***********/lib/python3.8/site-packages/botocore/retryhandler.py", line 359, in _check_caught_exception
raise caught_exception
File "***********/lib/python3.8/site-packages/botocore/endpoint.py", line 197, in _do_get_response
responses = self._event_emitter.emit(event_name, request=request)
File "***********/lib/python3.8/site-packages/botocore/hooks.py", line 356, in emit
return self._emitter.emit(aliased_event_name, **kwargs)
File "***********/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit
return self._emit(event_name, kwargs)
File "***********/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit
response = handler(**kwargs)
File "***********/lib/python3.8/site-packages/moto/core/models.py", line 363, in __call__
status, headers, body = response_callback(
    File "***********/lib/python3.8/site-packages/moto/core/responses.py", line 202, in dispatch
return cls()._dispatch(*args, **kwargs)
File "***********/lib/python3.8/site-packages/moto/core/responses.py", line 312, in _dispatch
return self.call_action()
File "***********/lib/python3.8/site-packages/moto/core/responses.py", line 402, in call_action
response = method()
File "***********/lib/python3.8/site-packages/moto/events/responses.py", line 121, in list_rules
rules = self.events_backend.list_rules(prefix, next_token, limit)
File "***********/lib/python3.8/site-packages/moto/events/models.py", line 639, in list_rules
start_index, end_index, new_next_token = self._process_token_and_limits(
    File "***********/lib/python3.8/site-packages/moto/events/models.py", line 563, in _process_token_and_limits
new_next_token = self._gen_next_token(end_index)
File "***********/lib/python3.8/site-packages/moto/events/models.py", line 547, in _gen_next_token
token = os.urandom(128).encode("base64")
AttributeError: 'bytes' object has no attribute 'encode'
```

Without the `Limit` parameter it works properly.

**Comment by bblommers** [comment]
Thanks for raising this @dashsatish. Looks like this only works in Py2.7, but not in 3.x. 

Marking it as a bug.

**Comment by salvacorts** [comment]
I'm still facing this issue (using localstack 3.5). The stack trace goes down to moto:
```
localstack-main   |   File "/opt/code/localstack/.venv/lib/python3.11/site-packages/moto/events/models.py", line 1036, in _gen_next_token
localstack-main   |     token = os.urandom(128).encode("base64")  # type: ignore
localstack-main   |             ^^^^^^^^^^^^^^^^^^^^^^
localstack-main   | AttributeError: 'bytes' object has no attribute 'encode'
```

Looks like this line is still present in the repo
https://github.com/getmoto/moto/blob/master/moto/events/models.py#L1036
